### PR TITLE
Events are being created and displayed

### PR DESCRIPTION
**Pull request by tusmanakhter**
Events are created and displayed, there are still some bugs which are
not related to events which are present. #112

Also The ringId of which ring the event belongs to and the person who
created the event should be stored in the events collection.

### CODE REVIEW

**Comment by kpamela** [comment]
For some reason, it is still not working,
https://cdn.discordapp.com/attachments/273937345458470914/297442058510008321/unknown.png
it creates the collection for half a second and it dissapears, same issue as before.

**Comment by tusmanakhter** [comment]
Hmmm that is very strange, it is working on my computer with no problem...I will get Taj to check on his computer.

**Review by taj-ch — APPROVED** [review]
Changes are working on my station. Both for firefox and internet edge are working fine.

**Comment by kpamela** [comment]
Had to re-clone, works now.

**Review by kpamela — APPROVED** [review]

**Pull request merged**
