### PR TITLE
Pam 4.1 - Templates simplified

### PR DESCRIPTION
**Pull request by kpamela**
TLDR commit; Ring templates simplified, one template for displaying any ring as a list an enhancement for #92

### CODE REVIEW

**Comment by tusmanakhter** [comment]
I am getting some errors when running the code
pic

**Comment by kpamela** [comment]
Which page are you on when this occurs? @tusmanakhter

**Review by tusmanakhter — CHANGES_REQUESTED** [review]
Fix function and variable visibility for rings page

**Review by tusmanakhter — APPROVED** [review]

**Comment by tusmanakhter** [comment]
All server tests passed and the client side looks great. Great job Pam!

**Pull request merged**
